/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistema.presentation.login;

import java.awt.Color;
import java.util.Arrays;
import java.util.Observable;
import java.util.Observer;
import javax.swing.JOptionPane;
import sistema.logic.Usuario;

/**
 *
 * @author Rachel
 */
public class LoginView extends javax.swing.JFrame implements Observer{
    
    LoginController controller;
    LoginModel model;

    public LoginController getController() {
        return controller;
    }

    public LoginModel getModel() {
        return model;
    }

    public void setController(LoginController controller) {
        this.controller = controller;
    }

    public void setModel(LoginModel model) {
        this.model = model;
        model.addObserver(this);
    }
    
    

    /**
     * Creates new form LoginView
     */
    public LoginView() {
        initComponents();
        this.getRootPane().setDefaultButton(loginBttn); //si se da "enter", reacciona el boton de login.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userLbl = new javax.swing.JLabel();
        passLbl = new javax.swing.JLabel();
        userFld = new javax.swing.JTextField();
        passFld = new javax.swing.JPasswordField();
        loginBttn = new javax.swing.JButton();
        exitBttn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Login");
        setMinimumSize(new java.awt.Dimension(284, 200));
        setPreferredSize(new java.awt.Dimension(284, 132));

        userLbl.setText("Username");

        passLbl.setText("Password");

        loginBttn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistema/presentation/iconos/login/login.png"))); // NOI18N
        loginBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBttnActionPerformed(evt);
            }
        });

        exitBttn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistema/presentation/iconos/login/exit.png"))); // NOI18N
        exitBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBttnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(userLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(userFld, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(passLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(passFld))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(loginBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(exitBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userLbl)
                    .addComponent(userFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passLbl)
                    .addComponent(passFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(loginBttn)
                    .addComponent(exitBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void exitBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBttnActionPerformed
        this.controller.exit();
    }//GEN-LAST:event_exitBttnActionPerformed

    private void loginBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBttnActionPerformed
        if(this.validar()){
            try{
                controller.login(this.usuario());
            }
            catch(Exception ex){
                this.mensaje(ex.getMessage());
            }
        }else{
            this.mensaje("Complete todo los datos");
        }
    }//GEN-LAST:event_loginBttnActionPerformed

    public Usuario usuario(){
        Usuario login = new Usuario();
        login.setUsuarioUsername(this.userFld.getText());
        login.setUsuarioPassword(new String(this.passFld.getPassword()));
        
        return login;
    }

    public boolean validar(){
        boolean correcto = true;
        this.limpiarErrores();
        
        if(this.userFld.getText().isEmpty()){
            correcto = false;
            this.userLbl.setForeground(Color.red);
        }    
        
        if(this.passFld.getPassword().length == 0){
            correcto = false;
            this.passLbl.setForeground(Color.red);
        }
        
        return correcto;
    }
    
    public void mensaje(String mensaje){
        JOptionPane.showMessageDialog(this, mensaje, "ERROR", JOptionPane.ERROR_MESSAGE);
    }
    
    public void limpiarErrores(){
        this.userLbl.setForeground(Color.black);
        this.passLbl.setForeground(Color.black);
    }
    
    public void llenarDatos(Usuario act){
        this.userFld.setText(act.getUsuarioUsername());
        this.passFld.setText(act.getUsuarioPassword());
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exitBttn;
    private javax.swing.JButton loginBttn;
    private javax.swing.JPasswordField passFld;
    private javax.swing.JLabel passLbl;
    private javax.swing.JTextField userFld;
    private javax.swing.JLabel userLbl;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg) {
        this.limpiarErrores();
        Usuario actual = model.getUsuario();
        this.llenarDatos(actual);
    }
}
